### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by MMaurel** [schmupu/ioBroker.sia#21]
**Describe the bug**  
Trying to install the adapter and getting "fetchPackageMetaData error for iobroker.sia@1.0.4 Cannot read property 'resolve' of undefined"

**To Reproduce**  
1. With ioBroker, try to add the adapter

**Expected behavior**  
Getting the adapter added and ready to be configured

**Screenshots & Logfiles**  
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'iobroker.sia@1.0.4',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v12.20.1
4 verbose npm-session c2fa4b8b4a4bcd5d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for iobroker.sia@1.0.4 Cannot read property 'resolve' of undefined
8 timing stage:rollbackFailedOptional Completed in 10ms
9 timing stage:runTopLevelLifecycles Completed in 11315ms
10 verbose stack TypeError: Cannot read property 'resolve' of undefined
10 verbose stack     at regFetch (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js:88:23)
10 verbose stack     at fetchPackument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:42:10)
10 verbose stack     at packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:20:10)
10 verbose stack     at getManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:22:10)
10 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:13:10)
10 verbose stack     at Object.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/index.js:17:12)
10 verbose stack     at Object.Fetcher#manifest [as manifest] (/usr/local/lib/node_modules/npm/node_modules/genfun/lib/genfun.js:15:38)
10 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetch.js:23:18)
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/manifest.js:24:12
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:29:24
10 verbose stack     at Promise._execute (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/debuggability.js:313:9)
10 verbose stack     at Promise._resolveFromExecutor (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:488:18)
10 verbose stack     at new Promise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:79:10)
10 verbose stack     at _inflight (/usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:28:25)
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:22:14
10 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose cwd /opt/iobroker
12 verbose Linux 4.14.72v7-aufs
13 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "iobroker.sia@1.0.4" "--loglevel" "error" "--prefix" "/opt/iobroker"
14 verbose node v12.20.1
15 verbose npm  v6.14.10
16 error Cannot read property 'resolve' of undefined
17 verbose exit [ 1, true ]

**Versions:**  
 - Adapter version: 4.1.11
 - JS-Controller version: 3.1.6
 - Node version: 14.15.4
 - Operating system: Raspbian (Debian for RaspberryPi)

**Comment by schmupu** [comment]
please do not use node 14 with the adapter
